services:
  - type: web
    name: olympus-tornei-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/public/tournaments
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_MODE
        value: "?sslmode=require"
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
