spring.application.name=backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:olympus_tornei}
spring.datasource.username=${DB_USER:olympus}
spring.datasource.password=${DB_PASSWORD:olympus}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
